### ISSUE TITLE
Variables are defined in the header

### ISSUE THREAD

**Issue by NomAnor** [MrVallentin/vkel#2]
The header can't be included multiple times because all variables are defined in the header, not declared.

This line in vkel.h

```
PFN_vkAcquireNextImageKHR __vkAcquireNextImageKHR;
```

should be

```
extern PFN_vkAcquireNextImageKHR __vkAcquireNextImageKHR;
```

and the old line should be in the vkel.c file.

This needs to be done for all lines from `// Instance and device extension names` until `#define vkAcquireNextImageKHR __vkAcquireNextImageKHR`.
For a quick fixed I copied the generator lines but it would be better to put them in a seperate function.

**Comment by vallentin** [comment]
I haven't extensively tested this yet. Just wanted to get a fix out, so I'll verify that everything works tomorrow!

> For a quick fixed I copied the generator lines but it would be better to put them in a seperate function.

I did so as well. But I've been planning on doing a rewrite of the generator, since it's gotten pretty messy.
