### ISSUE TITLE
Check for extension or layer always returns true

### ISSUE THREAD

**Issue by char8t** [MrVallentin/vkel#5]
There is a problem checking for extension/layer support atleast on android-64 (other platforms untested).

The runtime check via vkelIsInstanceExtensionSupported as well as the if-check eg. VKEL_KHR_win32_surface always returns true on android-64.

However getting all supported extension names work as expected.

I dont have looked through the implementation yet. Also I cannot test it on other platforms currently.

**Comment by m-vz** [comment]
I believe this relates to issue #6.

**Comment by char8t** [comment]
I close this isse in favour of the more specific issue #6.
